version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: npm start
    networks:
      - propmap_network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - propmap_network

networks:
  propmap_network:
    driver: bridge
